version: '3'
services:
  redis:
    image: 'redislabs/redismod'
  web1:
    image: 'paowick/swarm01_web:1.0'
    hostname: web1
  web2:
    image: 'paowick/swarm01_web:1.0'
    hostname: web2
  nginx:
    image: 'paowick/swarm01_nginx:1.0'
    ports:
    - '81:80'
    depends_on:
    - web1
    - web2